services:
  db:
    image: postgres:latest
    container_name: sea_pay_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sea_pay
    ports:
      - '5432:5432'
    command: -p 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sea_pay_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/sea_pay?schema=public"
    command: /bin/sh -c "npm run migrate && npm run start:dev"